name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  job_build_debug_plugin:
    name: Build plugin using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "plugin_binaries"
      flags: "DEBUG=1"

  job_build_debug_app:
    name: Build ethereum using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      app_repository: LedgerHQ/app-ethereum
      app_branch_name: develop
      upload_app_binaries_artifact: "eth_binaries"
      flags: "DEBUG=1 BYPASS_SIGNATURES=1"

  jobs-e2e-tests:
    name: E2E Tests
    needs: [job_build_debug_plugin, job_build_debug_app]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download built binaries
        uses: actions/download-artifact@v4
        with:
          name: plugin_binaries
          path: plugin_binaries

      - name: Download built binaries
        uses: actions/download-artifact@v4
        with:
          name: eth_binaries
          path: eth_binaries

      - name: Dispatch binaries
        run: |
          mkdir tests/elfs

          mv plugin_binaries/nanox/bin/app.elf tests/elfs/plugin_nanox.elf
          mv plugin_binaries/nanos2/bin/app.elf tests/elfs/plugin_nanosp.elf
          mv plugin_binaries/flex/bin/app.elf tests/elfs/plugin_flex.elf
          mv plugin_binaries/stax/bin/app.elf tests/elfs/plugin_stax.elf

          mv eth_binaries/nanox/bin/app.elf tests/elfs/ethereum_nanox.elf
          mv eth_binaries/nanos2/bin/app.elf tests/elfs/ethereum_nanosp.elf
          mv eth_binaries/flex/bin/app.elf tests/elfs/ethereum_flex.elf
          mv eth_binaries/stax/bin/app.elf tests/elfs/ethereum_stax.elf

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"

      - name: Install yarn
        run: |
          npm install -g yarn

      - name: Install JS deps
        run: |
          cd tests && yarn install

      - name: Run Zemu tests
        run: |
          cd tests && yarn test
